COMUNAS_CHILE = {
    'Región de Arica y Parinacota': [
        ('arica', 'Arica'),
        ('camarones', 'Camarones'),
        ('putre', 'Putre'),
        ('general_lagos', 'General Lagos')
    ],
    'Región de Tarapacá': [
        ('iquique', 'Iquique'),
        ('alto_hospicio', 'Alto Hospicio'),
        ('pozo_almonte', 'Pozo Almonte'),
        ('camiña', 'Camiña'),
        ('colchane', 'Colchane'),
        ('huara', 'Huara'),
        ('pica', 'Pica')
    ],
    'Región de Antofagasta': [
        ('antofagasta', 'Antofagasta'),
        ('mejillones', 'Mejillones'),
        ('sierra_gorda', 'Sierra Gorda'),
        ('taltal', 'Taltal'),
        ('calama', 'Calama'),
        ('ollague', 'Ollagüe'),
        ('san_pedro_de_atacama', 'San Pedro de Atacama'),
        ('tocopilla', 'Tocopilla'),
        ('maria_elena', 'María Elena')
    ],
    'Región de Atacama': [
        ('copiapo', 'Copiapó'),
        ('caldera', 'Caldera'),
        ('tierra_amarilla', 'Tierra Amarilla'),
        ('chañaral', 'Chañaral'),
        ('diego_de_almagro', 'Diego de Almagro'),
        ('vallenar', 'Vallenar'),
        ('alto_del_carmen', 'Alto del Carmen'),
        ('freirina', 'Freirina'),
        ('huasco', 'Huasco')
    ],
    'Región de Coquimbo': [
        ('la_serena', 'La Serena'),
        ('coquimbo', 'Coquimbo'),
        ('andacollo', 'Andacollo'),
        ('la_higuera', 'La Higuera'),
        ('paihuano', 'Paihuano'),
        ('vicuna', 'Vicuña'),
        ('ovalle', 'Ovalle'),
        ('combarbala', 'Combarbalá'),
        ('monte_patria', 'Monte Patria'),
        ('punitaqui', 'Punitaqui'),
        ('rio_hurtado', 'Río Hurtado'),
        ('illapel', 'Illapel'),
        ('canela', 'Canela'),
        ('los_vilos', 'Los Vilos'),
        ('salamanca', 'Salamanca')
    ],
    'Región de Valparaíso': [
        ('valparaiso', 'Valparaíso'),
        ('casablanca', 'Casablanca'),
        ('concon', 'Concón'),
        ('juan_fernandez', 'Juan Fernández'),
        ('puchuncavi', 'Puchuncaví'),
        ('quintero', 'Quintero'),
        ('vina_del_mar', 'Viña del Mar'),
        ('isla_de_pascua', 'Isla de Pascua'),
        ('los_andes', 'Los Andes'),
        ('calle_larga', 'Calle Larga'),
        ('rinconada', 'Rinconada'),
        ('san_esteban', 'San Esteban'),
        ('la_ligua', 'La Ligua'),
        ('cabildo', 'Cabildo'),
        ('papudo', 'Papudo'),
        ('petorca', 'Petorca'),
        ('zapallar', 'Zapallar'),
        ('quillota', 'Quillota'),
        ('calera', 'La Calera'),
        ('hijuelas', 'Hijuelas'),
        ('la_cruz', 'La Cruz'),
        ('nogales', 'Nogales'),
        ('san_antonio', 'San Antonio'),
        ('algarrobo', 'Algarrobo'),
        ('cartagena', 'Cartagena'),
        ('el_quisco', 'El Quisco'),
        ('el_tabo', 'El Tabo'),
        ('santo_domingo', 'Santo Domingo'),
        ('san_felipe', 'San Felipe'),
        ('catemu', 'Catemu'),
        ('llay_llay', 'Llay-Llay'),
        ('panquehue', 'Panquehue'),
        ('putaendo', 'Putaendo'),
        ('santa_maria', 'Santa María'),
        ('quilpue', 'Quilpué'),
        ('limache', 'Limache'),
        ('olmué', 'Olmué'),
        ('villa_alemana', 'Villa Alemana')
    ],
    'Región Metropolitana de Santiago': [
        ('santiago', 'Santiago'),
        ('cerrillos', 'Cerrillos'),
        ('cerro_navia', 'Cerro Navia'),
        ('conchali', 'Conchalí'),
        ('el_bosque', 'El Bosque'),
        ('estacion_central', 'Estación Central'),
        ('huechuraba', 'Huechuraba'),
        ('independencia', 'Independencia'),
        ('la_cisterna', 'La Cisterna'),
        ('la_florida', 'La Florida'),
        ('la_granja', 'La Granja'),
        ('la_pintana', 'La Pintana'),
        ('la_reina', 'La Reina'),
        ('las_condes', 'Las Condes'),
        ('lo_barnechea', 'Lo Barnechea'),
        ('lo_espejo', 'Lo Espejo'),
        ('lo_prado', 'Lo Prado'),
        ('macul', 'Macul'),
        ('maipu', 'Maipú'),
        ('nunoa', 'Ñuñoa'),
        ('pedro_aguirre_cerda', 'Pedro Aguirre Cerda'),
        ('penalolen', 'Peñalolén'),
        ('providencia', 'Providencia'),
        ('pudahuel', 'Pudahuel'),
        ('quilicura', 'Quilicura'),
        ('quinta_normal', 'Quinta Normal'),
        ('recoleta', 'Recoleta'),
        ('renca', 'Renca'),
        ('san_joaquin', 'San Joaquín'),
        ('san_miguel', 'San Miguel'),
        ('san_ramon', 'San Ramón'),
        ('vitacura', 'Vitacura'),
        ('puente_alto', 'Puente Alto'),
        ('pirque', 'Pirque'),
        ('san_jose_de_maipo', 'San José de Maipo'),
        ('colina', 'Colina'),
        ('lampa', 'Lampa'),
        ('tiltil', 'Tiltil'),
        ('san_bernardo', 'San Bernardo'),
        ('buin', 'Buin'),
        ('calera_de_tango', 'Calera de Tango'),
        ('paine', 'Paine'),
        ('melipilla', 'Melipilla'),
        ('alhue', 'Alhué'),
        ('curacavi', 'Curacaví'),
        ('maria_pinto', 'María Pinto'),
        ('san_pedro', 'San Pedro'),
        ('talagante', 'Talagante'),
        ('el_monte', 'El Monte'),
        ('isla_de_maipo', 'Isla de Maipo'),
        ('padre_hurtado', 'Padre Hurtado'),
        ('penaflor', 'Peñaflor')
    ],
    'Región de O’Higgins': [
        ('rancagua', 'Rancagua'),
        ('machali', 'Machalí'),
        ('requegua', 'Requinoa'),
        ('rengo', 'Rengo'),
        ('san_vicente', 'San Vicente')
    ],
    'Región del Biobío': [
        ('concepcion', 'Concepción'),
        ('coronel', 'Coronel'),
        ('chiguayante', 'Chiguayante'),
        ('florida', 'Florida'),
        ('hualqui', 'Hualqui'),
        ('lota', 'Lota'),
        ('penco', 'Penco'),
        ('san_pedro_de_la_paz', 'San Pedro de la Paz'),
        ('santa_juana', 'Santa Juana'),
        ('talcahuano', 'Talcahuano'),
        ('tomé', 'Tomé'),
        ('hualpen', 'Hualpén'),
        ('lebu', 'Lebu'),
        ('arauco', 'Arauco'),
        ('cañete', 'Cañete'),
        ('contulmo', 'Contulmo'),
        ('curanilahue', 'Curanilahue'),
        ('los_alamos', 'Los Álamos'),
        ('tirua', 'Tirúa'),
        ('los_angeles', 'Los Ángeles'),
        ('antuco', 'Antuco'),
        ('cabrero', 'Cabrero'),
        ('laja', 'Laja'),
        ('mulchen', 'Mulchén'),
        ('Nacimiento', 'Nacimiento'),
        ('negrete', 'Negrete'),
        ('quilleco', 'Quilleco'),
        ('san_rosendo', 'San Rosendo'),
        ('santa_barbara', 'Santa Bárbara'),
        ('tucapel', 'Tucapel'),
        ('yumbel', 'Yumbel'),
        ('alto_biobio', 'Alto Biobío')
    ],
    'Región de La Araucanía': [
        ('temuco', 'Temuco'),
        ('carahue', 'Carahue'),
        ('cholchol', 'Cholchol'),
        ('cunco', 'Cunco'),
        ('curarrehue', 'Curarrehue'),
        ('freire', 'Freire'),
        ('galvarino', 'Galvarino'),
        ('gorbea', 'Gorbea'),
        ('lautaro', 'Lautaro'),
        ('loncoche', 'Loncoche'),
        ('melipeuco', 'Melipeuco'),
        ('nueva_imperial', 'Nueva Imperial'),
        ('padre_las_casas', 'Padre Las Casas'),
        ('perquenco', 'Perquenco'),
        ('pitrufquen', 'Pitrufquén'),
        ('pucon', 'Pucón'),
        ('saavedra', 'Saavedra'),
        ('teodoro_schmidt', 'Teodoro Schmidt'),
        ('tolten', 'Toltén'),
        ('vilcun', 'Vilcún'),
        ('villarrica', 'Villarrica'),
        ('anguco', 'Angol'),
        ('collipulli', 'Collipulli'),
        ('curacautin', 'Curacautín'),
        ('ercilla', 'Ercilla'),
        ('lonquimay', 'Lonquimay'),
        ('los_sauces', 'Los Sauces'),
        ('lumaco', 'Lumaco'),
        ('puren', 'Purén'),
        ('renaico', 'Renaico'),
        ('traiguen', 'Traiguén'),
        ('victoria', 'Victoria')
    ],
    'Región de Los Ríos': [
        ('valdivia', 'Valdivia'),
        ('corral', 'Corral'),
        ('lanco', 'Lanco'),
        ('los_lagos', 'Los Lagos'),
        ('mafil', 'Máfil'),
        ('mariquina', 'Mariquina'),
        ('paillaco', 'Paillaco'),
        ('panguipulli', 'Panguipulli'),
        ('la_union', 'La Unión'),
        ('futrono', 'Futrono'),
        ('lago_ranco', 'Lago Ranco'),
        ('rio_bueno', 'Río Bueno')
    ],
    'Región de Los Lagos': [
        ('puerto_montt', 'Puerto Montt'),
        ('calbuco', 'Calbuco'),
        ('cochamo', 'Cochamó'),
        ('fresia', 'Fresia'),
        ('frutillar', 'Frutillar'),
        ('los_muermos', 'Los Muermos'),
        ('llanquihue', 'Llanquihue'),
        ('maullin', 'Maullín'),
        ('puerto_varas', 'Puerto Varas'),
        ('castro', 'Castro'),
        ('ancud', 'Ancud'),
        ('chonchi', 'Chonchi'),
        ('curaco_de_veles', 'Curaco de Vélez'),
        ('dalcahue', 'Dalcahue'),
        ('puqueldon', 'Puqueldón'),
        ('queilen', 'Queilén'),
        ('quinchao', 'Quinchao'),
        ('quellon', 'Quellón'),
        ('osorno', 'Osorno'),
        ('puerto_octay', 'Puerto Octay'),
        ('purranque', 'Purranque'),
        ('puyehue', 'Puyehue'),
        ('rio_negro', 'Río Negro'),
        ('san_juan_de_la_costa', 'San Juan de la Costa'),
        ('san_pablo', 'San Pablo'),
        ('chonchi', 'Chonchi')
    ],
        'Región de Aysén': [
        ('coyhaique', 'Coyhaique'),
        ('lago_verde', 'Lago Verde'),
        ('aisen', 'Aisén'),
        ('cisnes', 'Cisnes'),
        ('guaitecas', 'Guaitecas'),
        ('cochrane', 'Cochrane'),
        ('ohiggins', 'O’Higgins'),
        ('tortel', 'Tortel'),
        ('chile_chico', 'Chile Chico'),
        ('rio_ibanez', 'Río Ibáñez')
    ],
    'Región de Magallanes y de la Antártica Chilena': [
        ('punta_arenas', 'Punta Arenas'),
        ('laguna_blanca', 'Laguna Blanca'),
        ('rio_verde', 'Río Verde'),
        ('san_gregorio', 'San Gregorio'),
        ('cabo_de_hornos', 'Cabo de Hornos'),
        ('antartica', 'Antártica'),
        ('porvenir', 'Porvenir'),
        ('primavera', 'Primavera'),
        ('timaukel', 'Timaukel'),
        ('natales', 'Natales'),
        ('torres_del_paine', 'Torres del Paine')
    ],
    'Región de Ñuble': [
        ('chillan', 'Chillán'),
        ('bulnes', 'Bulnes'),
        ('coihueco', 'Coihueco'),
        ('cobquecura', 'Cobquecura'),
        ('coelemu', 'Coelemu'),
        ('el_carmen', 'El Carmen'),
        ('ninhue', 'Ninhue'),
        ('pemuco', 'Pemuco'),
        ('pinto', 'Pinto'),
        ('portezuelo', 'Portezuelo'),
        ('quirihue', 'Quirihue'),
        ('ranquil', 'Ránquil'),
        ('san_carlos', 'San Carlos'),
        ('san_fabian', 'San Fabián'),
        ('san_ignacio', 'San Ignacio'),
        ('san_nicolas', 'San Nicolás'),
        ('trehuaco', 'Treguaco'),
        ('yungay', 'Yungay')
    ]
}

# Función para obtener las comunas de una región específica
def obtener_comunas_por_region(region):
    return COMUNAS_CHILE.get(region, [])
