"""Crear tabla Sale

Revision ID: 65c7fd30f473
Revises: 771f889b8a44
Create Date: 2024-10-07 21:19:50.000431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c7fd30f473'
down_revision = '771f889b8a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
#     'sale',
#     db.Column('id', db.Integer, primary_key=True),
#     db.Column('user_id', db.Integer, db.ForeignKey('user.id'), nullable=False),
#     db.Column('client_id', db.Integer, db.ForeignKey('clients.id'), nullable=False),
#     db.Column('date', db.DateTime, nullable=False, default=datetime.utcnow),
#     db.Column('total_price', db.Numeric, nullable=False),
# )

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sale', ['sale_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sale_id')

    op.drop_table('sale')
    # ### end Alembic commands ###
